config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "posts#index"
  devise_for :users
  resources :posts do
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles: { thumb: "80x80>",mini: "25x25>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?
  before_action :set_locale
  def set_locale
    I18n.locale=params[:locale]||I18n.default_locale
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post

  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user= current_user

    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post=Post.find(params[:post_id])
      #@comment = @post.comments.find(params[:id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index

    if params[:user]
      @posts = Post.where(user: params[:user]).order("created_at DESC")
    else
       @posts = Post.all.order("created_at DESC")
    end
    @post=Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @likeds=Like.where(post: @post).all
    @comments=@post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @l=Like.new
    @l.post=@post
    @l.user=current_user
    @l.save
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  def unlike
    @l=Like.where(post:@post,user:current_user).first
    @l.destroy
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
 <div class="col-md-9">
  <div class="form-group">
    <%= f.text_field :bdy, id: :comment_bdy, class:"form-control" %>
  </div>
  </div>
  <div class="col-md-3">
  <div class="actions">
    <%= f.submit t('Acomment'), class:"form-action btn btn-info" %>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%=image_tag @comment.user.image.url(:mini) if @comment.user.image? %> <em><%=@comment.user.name%> </em> <b> <%=@comment.bdy%> </b><br/>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adem YAĞMURLU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-static-top">
    <nav class="navbar" style='background-color:#ddd'>
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><%= t 'Softwareengineering' %></a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="https://<%=request.host%>"><%= t 'Homepage' %></a></li>
          <li><a href="#"><%= t 'Programs' %></a></li>
          <li><a href="#"><%= t 'Graphicsanddesign' %></a></li>
          <li><a href="?locale=fr"><IMG src='<%= image_path('france.ico') %>' width='15' height='15' /> Français</a></li>
          <li><a href="?locale=tr"><IMG src='<%= image_path('turkey.ico') %>' width='15' height='15' /> Türkçe</a></li>
          <li><a href="?locale=en"><IMG src='<%= image_path('england.ico') %>' width='15' height='15' /> English</a></li>
          <li> <%= link_to t('NewTopic'), new_post_path, class:"glyphicon glyphicon-share" %> </li>
       
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default"><%= t('Search')%></button>
           </form>
            <% if user_signed_in? %>
              <em><%=image_tag current_user.image.url(:mini) if current_user.image?%> </em>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.name%> <span class="caret"></span></a>
                <ul class="dropdown-menu">
              <li><%= link_to t("LogOut"), destroy_user_session_path, class:"glyphicon glyphicon-log-out", :method => :delete %></li>
              <li><%= link_to t("Edit"), edit_user_registration_path, class:"glyphicon glyphicon-share"%></li>
            </ul>
          </li>
        <% else %>
           <li><%= link_to(t('SignIn'), new_user_session_path, class:"glyphicon glyphicon-log-in") %></li>
           <li><%= link_to(t('SignUp'), new_user_registration_path, class:"glyphicon glyphicon-user") %></li>
        <% end %> 
         </ul>
      </div>
    </nav>
</div>
<DIV class='container-fluid'>
      <DIV class='row'>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active"><CENTER>
      <img src="<%= image_url('01.jpg') %>" alt="...">
      <div class="carousel-caption">
      	<h3>Yazılım Çözümleri</h3>
      </div>
      </CENTER>
    </div>
    <div class="item">
      <CENTER>
      <img src="<%= image_url('02.jpg') %>" alt="...">
      <div class="carousel-caption">
      	<h3>Mühendislik Alanındaki Yenilikler</h3>
      </div>
      </CENTER>
    </div>
    <div class="item">
      <CENTER>
      <img src="<%= image_url('03.jpg') %>" alt="...">
      <div class="carousel-caption">
      	<h3>Gençliğe Sen de Bir Şans Ver</h3>
      </div>
      </CENTER>
    </div>
  </div>
 
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
        <DIV '!important' class='container-fluid row'>
          <ASIDE class='col-md-4 col-lg-3'>
            <DIV>DUYURULAR</DIV>
            <DIV class='jumbotron' ><H3>Yazılım Mühendisi</H3><P>Konusunda uzman personel aranıyor.</P></DIV>
          </ASIDE>
          <div class="col-md-8 col-lg-9 content">
            <%= yield %>
          </div>
           <SECTION class='col-md-8'>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </SECTION>

        </DIV>
      </DIV>
    </DIV>

<!-- Collect the nav links, forms, and other content for toggling -->

 <div class="container-fluid main-container">
  <footer  style='text-align:center'>
         <%=t('Site_Footer')%>
  </footer>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, remote: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :msg %>
    <%= form.text_area :msg, id: :post_msg,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Oluştur", class:"form-control btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
    <div class="container">
        <div class="row">
          <% @posts.each do |post| %>

            <div class="panel panel-default widget">

                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1">
                                    <%=image_tag post.user.image.url(:thumb) if post.user.image?%>
                                </div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <div class="mic-info">
                                             <a href="?user=<%=post.user.id%>"> <%=post.user.name%> </a> <%=post.created_at%>
                                        </div>
                                    </div>
                                    <div class="comment-text">
                                        <%=link_to post.title,post%> <br/>
                                        <%=image_tag post.image.url(:medium),class:"img img-responsive" if post.image?%>
                                        <br/>
                                        <%=post.msg%>
                                    </div>
                                    <hr>
                                    <div class="action">
                                      <%= link_to '', post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                                      <%= link_to '', edit_post_path(post),class:"glyphicon glyphicon-pencil" %>
                                      <%= link_to '', post_path(post),class:"glyphicon glyphicon-hand-right" %>
                                      <hr>
                                      <div id="<%=post.id%>">
                                      <%if Like.where(user:current_user, post:post).count>0%>
                                         <%= link_to "", unlike_post_path(post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                                      <%else%>
                                         <%= link_to "", like_post_path(post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                                      <%end%>
                                      </div>
                                      <hr>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <%end%>
        </div>
    </div>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="panel panel-default widget">
  <div class="panel-body">
    <%= render 'form', post: @post %>
  </div>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default widget">

    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                        <%=image_tag @post.user.image.url(:mini) if @post.user.image?%>
                    </div>
                    <div class="col-xs-10 col-md-11">
                        <div>
                            <div class="mic-info">
                                 <a href="?user=<%=@post.user.id%>"> <%=@post.user.name%> </a> <%=@post.created_at%>
                            </div>
                        </div>
                        <div class="comment-text">
                            <%=@post.title%> <br/>
                            <%=image_tag @post.image.url(:medium),class:"img img-responsive" if @post.image?%>
                            <br/>
                            <%=@post.msg%>
                        </div>
                        <hr>
                        <div class="action">
                          <%= link_to '', @post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                          <%= link_to '', edit_post_path(@post),class:"glyphicon glyphicon-pencil" %>

                          <div id="<%=@post.id%>">
                          <%if Like.where(user:current_user, post:@post).count>0%>
                             <%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                          <%else%>
                             <%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                          <%end%>
                          </div>
                        </div>
                        <hr>
                        <%=render 'comments/form'%>
                        Bunu beğenler(<%=@likeds.count%>) <br/>
                        <% @likeds.each do |l|%>
                          <%=l.user.name%>
                        <% end %>
                        <hr>
                        <div id="comments">
                        <%@comments.each do |c|%>
                         <%=image_tag c.user.image.url(:mini) if c.user.image?%> <em> <%=c.user.name%> </em> <b><%=c.bdy%> </b>    <br/>
                        <%end%>
                      </div>

                    </div>
            </li>
        </ul>
    </div>
</div>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>')